"""Katalog zdjec: klucz -> (plik zrodlowy z wermont.eu/wp-content/uploads, alt, pozycja kadru).
Wszystkie to realizacje Wermont z ich obecnej strony. Stockow i renderow AI z ich strony nie bierzemy."""

ZDJ = {
    # kuchnie
    'kuchnia-orzech-wyspa': ('realizacja-a-07.jpg', 'Kuchnia z wyspą i wysoką zabudową w ciemnym dekorze orzecha, przy wyspie hokery, na podłodze jodełka', '50% 60%'),
    'kuchnia-orzech-wyspa-2': ('realizacja-a-06.jpg', 'Wyspa kuchenna w dekorze orzecha z hokerami i wysoka zabudowa z przejściem do spiżarni', '50% 50%'),
    'kuchnia-orzech-blat': ('realizacja-a-02.jpg', 'Kuchnia w literę L w dekorze orzecha z jasnym blatem i oknem nad zlewem', '50% 50%'),
    'kuchnia-orzech-lodowka': ('realizacja-a-04.jpg', 'Kuchnia z wyspą, lodówka side by side w zabudowie z orzecha', '50% 50%'),
    'kuchnia-orzech-cargo': ('realizacja-a-01.jpg', 'Otwarte cargo w wyspie kuchennej obok wysokiej zabudowy z lodówką', '50% 50%'),
    'kuchnia-slupek-blachy': ('realizacja-a-03.jpg', 'Słupek z piekarnikiem, pod nim szuflada z pionowymi przegrodami na blachy', '50% 50%'),
    'kuchnia-naroznik-orzech': ('realizacja-a-05.jpg', 'Otwarta szafka narożna z wysuwanym narożnikiem w kuchni z orzecha', '50% 50%'),
    'kuchnia-dab-okno': ('DSC_4086.jpg', 'Jasna kuchnia w literę U z oknem nad blatem, białe szafki i wysoka zabudowa w dekorze dębu', '50% 55%'),
    'kuchnia-dab-okno-2': ('DSC_4089.jpg', 'Kuchnia z białymi frontami i dębowym blatem, wysoka zabudowa z czarną lodówką', '50% 55%'),
    'kuchnia-dab-wyspa': ('DSC_4061.jpg', 'Kuchnia z wyspą, białe szafki dolne i ściana zabudowy w dekorze dębu z czarną lodówką', '50% 55%'),
    'kuchnia-witryna': ('DSC_4080.jpg', 'Podświetlana witryna na szkło obok kuchni z wyspą i lampami nad blatem', '65% 55%'),
    'kuchnia-dab-lodowka': ('DSC_4034.jpg', 'Wysoka zabudowa w dekorze dębu z czarną lodówką i blatem przy wejściu do kuchni', '50% 50%'),
    'kuchnia-biala-slupki': ('DSC_3938.jpg', 'Biała wysoka zabudowa z dwoma piekarnikami w słupku', '50% 50%'),
    'kuchnia-blat-dab': ('DSC_3932.jpg', 'Narożnik dębowego blatu w jasnej kuchni', '50% 50%'),
    'kuchnia-granat': ('DSC_3001_SnapseedCopy.jpg', 'Kuchnia z granatowymi frontami, lodówką w zabudowie i jasnym blatem przy oknie', '50% 50%'),
    'kuchnia-granat-zabudowa': ('DSC_3042_SnapseedCopy.jpg', 'Granatowa zabudowa kuchenna od podłogi do sufitu z wbudowaną lodówką i złotymi uchwytami', '50% 50%'),
    'kuchnia-granat-biala': ('DSC_3074_SnapseedCopy.jpg', 'Jasna kuchnia w literę U z granatowymi szafkami i szklaną witryną', '50% 50%'),
    'kuchnia-granat-naroznik': ('DSC_3099.jpg', 'Wysuwany narożnik w granatowej szafce kuchennej', '50% 50%'),
    'kuchnia-cegla': ('DSC_2783_SnapseedCopy.jpg', 'Kuchnia z drewnianymi frontami przy ścianie z czerwonej cegły, czarna lodówka w zabudowie', '50% 50%'),
    'kuchnia-cegla-2': ('DSC_2728_SnapseedCopy.jpg', 'Kuchnia z frontami z drewna i okapem na tle ceglanej ściany', '50% 50%'),
    'kuchnia-czarny-blat': ('DSC_2743_SnapseedCopy.jpg', 'Czarny blat ze zlewem podwieszanym w drewnianej kuchni', '50% 50%'),
    'kuchnia-slupek-drewno': ('DSC_2820_SnapseedCopy-1.jpg', 'Słupek z piekarnikiem w zabudowie z drewna', '50% 50%'),
    'kuchnia-dab-b': ('realizacja-b-07.jpg', 'Wysoka zabudowa w dekorze dębu z piekarnikiem i kompaktowym piekarnikiem, podłoga w jodełkę', '50% 50%'),
    'kuchnia-dab-b-2': ('realizacja-b-06.jpg', 'Ściana wysokiej zabudowy w dekorze dębu z piekarnikami w słupku', '50% 50%'),
    'kuchnia-szuflady': ('realizacja-b-09.jpg', 'Otwarte szuflady Blum pod blatem w kuchni w dekorze dębu', '50% 50%'),
    'kuchnia-szuflady-2': ('realizacja-b-02.jpg', 'Szuflady wewnętrzne za frontem szafki dolnej', '50% 50%'),
    'kuchnia-cargo-dab': ('realizacja-b-05.jpg', 'Wysuwane cargo z szufladami w wysokiej zabudowie z dębu', '50% 50%'),
    'kuchnia-naroznik-dab': ('realizacja-b-01.jpg', 'Narożnik z wysuwanymi półkami w szafce kuchennej', '50% 50%'),
    'kuchnia-zlew': ('realizacja-b-03.jpg', 'Zlew podwieszany w jasnym blacie pod oknem', '50% 50%'),
    'kuchnia-mdf': ('mdf-1.jpg', 'Biała kuchnia z frontami z MDF, wysoka zabudowa i wyspa', '50% 50%'),
    'kuchnia-mdf-2': ('mdf-2.jpg', 'Wysoka biała zabudowa z frontami z MDF i piekarnikiem', '50% 50%'),
    'kuchnia-mdf-3': ('mdf-3.jpg', 'Szuflada z pełnym wysuwem w białej kuchni z MDF', '50% 50%'),
    'kuchnia-mdf-4': ('img_1617.jpg', 'Biała wysoka zabudowa z frontami z MDF i dwoma piekarnikami', '50% 50%'),
    'kuchnia-mdf-5': ('img_1589.jpg', 'Biała kuchnia z MDF z wysoką zabudową i wyspą', '50% 50%'),
    'bezuchwyt-blat': ('korytkowa-blat-1.jpg', 'Kuchnia bezuchwytowa z listwą korytkową pod blatem', '50% 50%'),
    'bezuchwyt-blat-2': ('korytkowa-blat-2.jpg', 'Blat w dekorze drewna nad frontami bez uchwytów', '50% 50%'),
    'bezuchwyt-egger': ('korytkowa-egger-1.jpg', 'Białe fronty bez uchwytów z listwą korytkową pod blatem', '50% 50%'),
    'bezuchwyt-szuflady': ('korytkowa-egger-2.jpg', 'Otwarte szuflady w kuchni bezuchwytowej', '50% 50%'),
    'bezuchwyt-zmywarka': ('korytkowa-peka-schuco.jpg', 'Zmywarka w zabudowie w kuchni bezuchwytowej z listwą Peka Schüco', '50% 50%'),
    'kuchnia-klasyczna': ('IMG_1059.jpg', 'Klasyczna kuchnia z frontami z drewna w kolorze kości słoniowej z patyną', '50% 50%'),
    'kuchnia-klasyczna-2': ('IMG_1087.jpg', 'Kuchnia w stylu klasycznym z frezowanymi frontami, okapem w obudowie i drewnianym blatem', '50% 50%'),
    'kuchnia-klasyczna-3': ('IMG_0592-3.jpg', 'Kuchnia klasyczna w literę L z frezowanymi frontami i drewnianym blatem', '50% 50%'),
    'kuchnia-klasyczna-4': ('IMG_1090.jpg', 'Kuchnia klasyczna z patynowanymi frontami i witrynami', '50% 50%'),
    # szafy
    'szafa-wneka': ('DSC_4096.jpg', 'Szafa wnękowa na całą ścianę przedpokoju, fronty w jasnym dekorze drewna', '50% 50%'),
    'garderoba-przedpokoj': ('DSC_3144_SnapseedCopy.jpg', 'Biała zabudowa przedpokoju z otwartą częścią na kurtki i szufladami', '50% 40%'),
    'szafa-szara': ('realizacja-c-01.jpg', 'Szara szafa z otwartymi półkami i siedziskiem w przedpokoju', '50% 50%'),
    'szafa-skos': ('szafa-w-skosie-zabudowa-poddasza.jpg', 'Szafa w skosie na poddaszu z półkami, drążkiem i szufladami', '50% 50%'),
    # lazienki
    'lazienka-dab': ('realizacja-b-08.jpg', 'Podwieszana szafka łazienkowa w dekorze dębu z dwiema umywalkami nablatowymi', '50% 50%'),
    'lazienka-dab-2': ('realizacja-b-04.jpg', 'Szafka łazienkowa w dekorze dębu z dwiema umywalkami i czarnymi bateriami podtynkowymi', '50% 50%'),
    'lazienka-szuflada': ('realizacja-b-10.jpg', 'Otwarta szuflada w podwieszanej szafce łazienkowej', '50% 50%'),
    'lazienka-szuflada-2': ('realizacja-b-11.jpg', 'Szuflada pod umywalką nablatową z organizerem', '50% 50%'),
    'lazienka-kamien': ('DSC_2854_SnapseedCopy.jpg', 'Szafka łazienkowa z drewna z zaokrąglonym blatem z kamienia i umywalką nablatową', '50% 50%'),
    'lazienka-drewno': ('DSC_2859_SnapseedCopy.jpg', 'Drewniana szafka pod umywalką na tle płytek w jodełkę', '50% 50%'),
    'lazienka-lustro': ('DSC_3222_SnapseedCopy.jpg', 'Łazienka z dwiema umywalkami nablatowymi na szafce i podświetlanym lustrem', '50% 50%'),
    # proces
    'pomiar': ('pomiar-kuchni-dalmierzem-wermont.jpg', 'Pomiar pomieszczenia na poddaszu, rzut rysowany na tablecie', '50% 50%'),
    'wizualizacja': ('wizualizacja-projektu-kuchni-wermont.jpg', 'Wizualizacja projektu kuchni z jasnymi frontami i blatem w dekorze drewna', '50% 50%'),
}
